### ISSUE TITLE
Show the benchmark result with table?

### ISSUE THREAD

**Issue by lexcao** [programatik29/rust-web-benchmarks#18]
### Background
It would be nice if there is a table showing the result of the benchmark between each web framework.

### Expectation
It is something like that:

| framework | Latencies.Avg | ... |  Requests.Total | ... | Transfer.Total | ... | Maximum Memory Usage |
| -- | -- | -- | -- | -- | -- | -- | -- |
| actix-web | 0.50ms | ... | 30178057 | ... | 3.65 GB | .. | 13.7 MB | 
| ... | 

### Anything else
I am willing to add this feature.

**Comment by programatik29** [comment]
All pull requests are welcome.

**Comment by programatik29** [comment]
Suggestion makes sense. I plan to add this if no one comes up with a pull request in few weeks.

**Comment by frederikhors** [comment]
Can you publish that table on Readme?

**Comment by programatik29** [comment]
@frederikhors I'll put comparison table at the top of result md file.

**Comment by frederikhors** [comment]
Can you write here when done, please?

**Comment by programatik29** [comment]
It is done.
