### ISSUE TITLE
Different Transfer per Request

### ISSUE THREAD

**Issue by mkadirtan** [programatik29/rust-web-benchmarks#23]
Even though Hyper and Axum have very close `request/sec` their `MB/sec` is very different. I believe this is due to the default headers returned by different frameworks. If all the frameworks respond with the same amount of data per request, that could change the results, but I am not sure by how much.

**Comment by programatik29** [comment]
I checked that out locally, difference isn't even visible since all transfers happen in localhost and extra headers don't add that much size per request.
