### ISSUE TITLE
Why is rewrk output different from formatted table?

### ISSUE THREAD

**Issue by TaeyoonKwon** [programatik29/rust-web-benchmarks#9]
In rewrk output, actix web double scores Rocket in requests but in the table rocket sends more. How can it be?

**Comment by programatik29** [comment]
I'm not sure. I didn't benchmark table formatted results.

@samal-rasmussen which parameters did you use for benchmarking?

**Comment by samal-rasmussen** [comment]
I ran the script exactly as is with no parameters `./hello-world-csv.sh`
https://github.com/programatik29/rust-web-benchmarks/blob/master/result/hello-world/csv/hello-world-csv.sh

**Comment by programatik29** [comment]
> I can the script exactly as is with no parameters `./hello-world-csv.sh` https://github.com/programatik29/rust-web-benchmarks/blob/master/result/hello-world/csv/hello-world-csv.sh

Can you tweak with thread(should be logical cpu core count) and connection count(try 1000, 2000) parameters and do some more benchmarks(5-10 seconds each should do). Your results seem inconsistent with my benchmark.

**Comment by programatik29** [comment]
Removed csv benchmark because it was hard to keep it updated with my results.

**Comment by samal-rasmussen** [comment]
Results will be different on different machines. If both benchmarks were run on the same machine then the results should be much more similar.
